### ISSUE TITLE
Quiz Lv3 Feedback

### ISSUE THREAD

**Issue by udiiin** [rahadi23/hsi-sandbox-lvl-3#1]
Halo Mas @rahadi23, terima kasih utk submissionnya.  
Mantab sekali udah pake TypeScript ✨ 

Secara functional udah oke 👍  
Ada error handlingnya jg 👍  
Code juga rapih 👍

Saya ada bbrp feedback minor:

**1.)**  
Di dalam getStaticPaths ada beberapa kali `getArticleList` (menggunakan while).  
Ini bisa sekali aja fetch articles dg kasih param `perPage: 999`.

**2.)**  
Fungsi `renderRelatedArticles` bisa dibikin component terpisah biar lebih rapi & lebih optimize

**3.)**  
Bisa manfaatkan object destructuring.

Before:
```js
const myFunction(param) {
  console.log(param.cat);
  console.log(param.fish);
}
```

After:
```js
const myFunction(param) {
  const { cat, fish } = param;
  console.log(cat);
  console.log(fish);
}
// atau
const myFunction({ cat, fish }) {
  console.log(cat);
  console.log(fish);
}
```

**4.)**  
Ketika di halaman detail page, bisa improve SEOnya dengan ubah `<title>` jadi judul artikel.

**5.)**  
Di sini, `const getStaticPaths: GetStaticPaths = async (context) => {`  
Param `context` gak dipakai, jadi bisa diilangin aja..

**6.)**  
`context.params?.["slug"]` bisa pakai `context.params?.slug`

.

Barokallaahu fiik 🙏

**Comment by rahadi23** [comment]
Halo Mas @udiiin, terima kasih buat feedbacknya. Maaf telat responsnya karena menyesuaikan kegiatan sehari-hari hehe

Untuk feedbacknya sudah saya perbaiki ya Mas, detilnya sebagai berikut:

> Di dalam `getStaticPaths` ada beberapa kali `getArticleList` (menggunakan while). Ini bisa sekali aja fetch articles dg kasih param `perPage: 999`.

Sudah saya perbaiki sebagai berikut (https://github.com/rahadi23/hsi-sandbox-lvl-3/commit/bc1f35c3cd48582a230e7abcf8e75c7678bb6f47):

https://github.com/rahadi23/hsi-sandbox-lvl-3/blob/bc1f35c3cd48582a230e7abcf8e75c7678bb6f47/pages/%5Bslug%5D/index.tsx#L24-L26

https://github.com/rahadi23/hsi-sandbox-lvl-3/blob/bc1f35c3cd48582a230e7abcf8e75c7678bb6f47/pages/%5Bslug%5D/related/index.tsx#L23-L25

<hr />

> Fungsi `renderRelatedArticles` bisa dibikin component terpisah biar lebih rapi & lebih optimize.

Sudah dipisahkan menjadi satu component bernama [`RelatedArticleHighlightList`](https://github.com/rahadi23/hsi-sandbox-lvl-3/blob/master/components/RelatedArticleHighlightList/RelatedArticleHighlightList.tsx) (https://github.com/rahadi23/hsi-sandbox-lvl-3/commit/fc579ea64d5bf35379e394f1d0ea301d6a01398e).

<hr />

> Bisa manfaatkan object destructuring.

Sudah diimplementasikan untuk `props` di semua component, sebagai berikut (https://github.com/rahadi23/hsi-sandbox-lvl-3/commit/a7f490333f5a4578320a30d88aec83b7c50781ae):

https://github.com/rahadi23/hsi-sandbox-lvl-3/blob/a7f490333f5a4578320a30d88aec83b7c50781ae/components/ArticleItem/ArticleItem.tsx#L11

https://github.com/rahadi23/hsi-sandbox-lvl-3/blob/a7f490333f5a4578320a30d88aec83b7c50781ae/components/ArticleList/ArticleList.tsx#L17

https://github.com/rahadi23/hsi-sandbox-lvl-3/blob/a7f490333f5a4578320a30d88aec83b7c50781ae/components/Header/Header.tsx#L11

https://github.com/rahadi23/hsi-sandbox-lvl-3/blob/a7f490333f5a4578320a30d88aec83b7c50781ae/components/NavButton/NavButton.tsx#L26

https://github.com/rahadi23/hsi-sandbox-lvl-3/blob/a7f490333f5a4578320a30d88aec83b7c50781ae/components/RelatedArticleHighlightItemCard/RelatedArticleHighlightItemCard.tsx#L11

https://github.com/rahadi23/hsi-sandbox-lvl-3/blob/a7f490333f5a4578320a30d88aec83b7c50781ae/components/RelatedArticleHighlightList/RelatedArticleHighlightList.tsx#L12-L15

https://github.com/rahadi23/hsi-sandbox-lvl-3/blob/a7f490333f5a4578320a30d88aec83b7c50781ae/components/RelatedArticleItemCard/RelatedArticleItemCard.tsx#L12

https://github.com/rahadi23/hsi-sandbox-lvl-3/blob/a7f490333f5a4578320a30d88aec83b7c50781ae/components/RelatedArticleList/RelatedArticleList.tsx#L17-L20

https://github.com/rahadi23/hsi-sandbox-lvl-3/blob/a7f490333f5a4578320a30d88aec83b7c50781ae/pages/%5Bslug%5D/index.tsx#L53

https://github.com/rahadi23/hsi-sandbox-lvl-3/blob/a7f490333f5a4578320a30d88aec83b7c50781ae/pages/%5Bslug%5D/related/index.tsx#L58-L62

https://github.com/rahadi23/hsi-sandbox-lvl-3/blob/a7f490333f5a4578320a30d88aec83b7c50781ae/pages/index.tsx#L47

<hr />

> Ketika di halaman detail page, bisa improve SEOnya dengan ubah <title> jadi judul artikel.

Sudah saya implementasikan sebagai berikut (https://github.com/rahadi23/hsi-sandbox-lvl-3/commit/fe3df5b45324ad3fd844b5c38c033ae5fbc39e97):

https://github.com/rahadi23/hsi-sandbox-lvl-3/blob/fe3df5b45324ad3fd844b5c38c033ae5fbc39e97/pages/%5Bslug%5D/index.tsx#L84-L86

https://github.com/rahadi23/hsi-sandbox-lvl-3/blob/fe3df5b45324ad3fd844b5c38c033ae5fbc39e97/pages/%5Bslug%5D/related/index.tsx#L66-L68

<hr />

> Di sini, `const getStaticPaths: GetStaticPaths = async (context) => {` Param `context` gak dipakai, jadi bisa diilangin aja..

Sudah saya hapus (https://github.com/rahadi23/hsi-sandbox-lvl-3/commit/a5025195c5960a22f6384fc93e61584b2cedd9c8).

<hr />

> `context.params?.["slug"]` bisa pakai `context.params?.slug`

Sudah saya sesuaikan sebagai berikut (https://github.com/rahadi23/hsi-sandbox-lvl-3/commit/d7bb90fd26fcecef60d1a9f575310f7a4e19433f):

https://github.com/rahadi23/hsi-sandbox-lvl-3/blob/d7bb90fd26fcecef60d1a9f575310f7a4e19433f/pages/%5Bslug%5D/index.tsx#L38

https://github.com/rahadi23/hsi-sandbox-lvl-3/blob/d7bb90fd26fcecef60d1a9f575310f7a4e19433f/pages/%5Bslug%5D/related/index.tsx#L38

<hr />

sekian, sekali lagi saya ucapkan terima kasih atas reviewnya Mas. Jazakumullahu khair.

**Comment by udiiin** [comment]
Terima kasih updatenya mas..  
Sipp udah mantab ✅ 

Bisa ke level selanjutnya 👍  
Barokallaahu fiik
